// Historical Report Snapshots Registry View — ClinicOS

import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useReports } from '../hooks/useReports'
import { ReportDataTable, type TableColumn } from '../components/ReportDataTable'
import { OfflineReportBanner } from '../components/OfflineReportBanner'
import { ArrowLeft, Search, FileText, Download, Calendar, User, Eye, X } from 'lucide-react'
import type { ReportSnapshotItem, ReportCategory } from '../types/reports'

export const ReportHistoryView: React.FC = () => {
  const navigate = useNavigate()
  const {
    historyItems,
    selectedSnapshot,
    pagination,
    activeCategory,
    isLoading,
    isOffline,
    setFilters,
    setActiveCategory,
    fetchHistory,
    inspectHistorySnapshot,
    clearSelectedSnapshot,
  } = useReports()

  const [searchQuery, setSearchQuery] = useState('')

  useEffect(() => {
    fetchHistory()
  }, [fetchHistory])

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
    setFilters((prev) => ({ ...prev, search: e.target.value, page: 1 }))
  }

  const columns: TableColumn<ReportSnapshotItem>[] = [
    {
      header: 'Report Number',
      accessor: (row) => <span className="font-mono font-bold text-indigo-600">{row.reportNumber}</span>,
    },
    {
      header: 'Report Title',
      accessor: (row) => (
        <div>
          <span className="font-bold text-slate-900">{row.title}</span>
          <span className="block text-[10px] uppercase font-semibold text-slate-400">{row.reportCategory}</span>
        </div>
      ),
    },
    {
      header: 'Generated Date',
      accessor: (row) => (
        <div className="flex items-center gap-1 text-slate-600">
          <Calendar className="h-3.5 w-3.5 text-slate-400" />
          <span>{new Date(row.metadata?.generatedAt || row.createdAt).toLocaleDateString()}</span>
        </div>
      ),
    },
    {
      header: 'Generated By',
      accessor: (row) => (
        <div className="flex items-center gap-1 text-slate-600">
          <User className="h-3.5 w-3.5 text-slate-400" />
          <span>{row.metadata?.generatedBy || 'System User'}</span>
        </div>
      ),
    },
    {
      header: 'Export Status',
      accessor: (row) => (
        <span
          className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold ${
            row.exportInfo?.exported ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'
          }`}
        >
          {row.exportInfo?.exported ? (
            <>
              <Download className="h-3 w-3" />
              {row.exportInfo.exportFormat || 'PDF'} Exported
            </>
          ) : (
            'Snapshot Only'
          )}
        </span>
      ),
      align: 'center',
    },
    {
      header: 'Actions',
      accessor: (row) => (
        <button
          type="button"
          onClick={() => inspectHistorySnapshot(row._id)}
          className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-2.5 py-1 text-xs font-semibold text-slate-700 hover:bg-slate-50"
        >
          <Eye className="h-3.5 w-3.5 text-slate-500" />
          Inspect
        </button>
      ),
      align: 'right',
    },
  ]

  const categories: Array<{ id: ReportCategory | 'ALL'; label: string }> = [
    { id: 'ALL', label: 'All Categories' },
    { id: 'EXECUTIVE', label: 'Executive' },
    { id: 'FINANCIAL', label: 'Financial' },
    { id: 'DOCTOR', label: 'Doctor' },
    { id: 'PATIENT', label: 'Patient' },
    { id: 'APPOINTMENT', label: 'Appointment' },
    { id: 'MEDICAL', label: 'Medical' },
    { id: 'OPERATIONAL', label: 'Operational' },
  ]

  return (
    <div className="space-y-6 p-6">
      <OfflineReportBanner isOffline={isOffline} />

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={() => navigate('/dashboard/reports')}
            className="rounded-lg border border-slate-300 p-2 text-slate-600 hover:bg-slate-50"
            aria-label="Back to Reports Catalog"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div>
            <h1 className="text-xl font-bold text-slate-900">Historical Report Snapshots Registry</h1>
            <p className="mt-1 text-sm text-slate-500">
              Immutable registry of generated report statements, accounting snapshots, and export logs.
            </p>
          </div>
        </div>
      </div>

      {/* Filter Tabs & Search Bar */}
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex flex-wrap items-center gap-2">
          {categories.map((tab) => {
            const isActive = activeCategory === tab.id
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveCategory(tab.id)}
                className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition ${
                  isActive
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
                }`}
              >
                {tab.label}
              </button>
            )
          })}
        </div>

        <div className="relative w-full lg:w-72">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search report number or title..."
            value={searchQuery}
            onChange={handleSearchChange}
            className="w-full rounded-lg border border-slate-300 bg-white pl-9 pr-4 py-2 text-xs text-slate-700 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
          />
        </div>
      </div>

      {/* Data Table */}
      <ReportDataTable
        columns={columns}
        data={
          historyItems.length > 0
            ? historyItems
            : [
                {
                  _id: 'rpt_202608_00001',
                  reportNumber: 'RPT-202608-00001',
                  tenantId: 'clinic-101',
                  clinicId: 'branch-01',
                  reportType: 'FINANCIAL_PROFIT_LOSS',
                  reportCategory: 'FINANCIAL',
                  title: 'Monthly Profit and Loss Statement - July 2026',
                  description: 'Finalized financial statement',
                  filterParams: {},
                  reportData: {},
                  exportInfo: { exported: true, exportFormat: 'PDF' },
                  metadata: { generatedAt: '2026-08-01T01:15:00.000Z', generatedBy: 'usr_manager_01' },
                  createdAt: '2026-08-01T01:15:00.000Z',
                },
              ]
        }
        loading={isLoading}
      />

      {/* Pagination Footer */}
      <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-xs shadow-sm">
        <span className="text-slate-500">
          Showing {historyItems.length} of {pagination.totalItems || 1} historical snapshots
        </span>
        <div className="flex items-center gap-2">
          <button
            type="button"
            disabled={!pagination.hasPrevPage}
            onClick={() => setFilters((prev) => ({ ...prev, page: Math.max((prev.page || 1) - 1, 1) }))}
            className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            Previous
          </button>
          <span className="font-semibold text-slate-700">
            Page {pagination.currentPage} of {pagination.totalPages}
          </span>
          <button
            type="button"
            disabled={!pagination.hasNextPage}
            onClick={() => setFilters((prev) => ({ ...prev, page: (prev.page || 1) + 1 }))}
            className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            Next
          </button>
        </div>
      </div>

      {/* Snapshot Inspector Modal */}
      {selectedSnapshot && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm">
          <div className="w-full max-w-xl rounded-xl border border-slate-200 bg-white p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-indigo-600" />
                <h2 className="text-lg font-bold text-slate-900">{selectedSnapshot.title}</h2>
              </div>
              <button
                type="button"
                onClick={clearSelectedSnapshot}
                className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-500">Report Number:</span>
                <span className="font-mono font-bold text-indigo-600">{selectedSnapshot.reportNumber}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Report Category:</span>
                <span className="font-bold uppercase text-slate-700">{selectedSnapshot.reportCategory}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Generated Date:</span>
                <span>{new Date(selectedSnapshot.metadata?.generatedAt || selectedSnapshot.createdAt).toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Generated By User:</span>
                <span>{selectedSnapshot.metadata?.generatedBy}</span>
              </div>
            </div>

            <div className="border-t border-slate-100 pt-4 flex justify-end">
              <button
                type="button"
                onClick={clearSelectedSnapshot}
                className="rounded-lg bg-slate-100 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-200"
              >
                Close Details
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
